version: '3.8'

services:
  mysql:
    image: mysql:8.1
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: db_clients
      MYSQL_USER: user_clients
      MYSQL_PASSWORD: password_clients