application:
  env: ${APPLICATION_ENV}
  name: '@pom.name@'
  description: '@pom.description@'
  version: '@pom.version@'

server:
  port: ${SERVER_PORT}

spring:
  flyway:
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USERNAME}
    password: ${SPRING_FLYWAY_PASSWORD}

jdbc:
  dbClients:
    url: ${JDBC_DBCLIENTS_URL}
    username: ${JDBC_DBCLIENTS_USERNAME}
    password: ${JDBC_DBCLIENTS_PASSWORD}